backend: elveflow
device_name: COM10
regulator_types:
- 5
- 5
- 0
- 0
calib_path: U:\PelliKAn\3_Filtration\4_Config\OB1_Calib_latest.txt
autoload_calib: true
pressure_limit: 2000.0
use_remote_measurement: false
channel_main: 1
channel_backwash: 2
