Controller Name: MUXst du oder was
COM Port: ASRL10::INSTR
Containers:
  1 Sample:
    MUX Valve: 1
    Maximum Volume: 180000
    Small Volume: 5000
  10 Sample:
    MUX Valve: 3
    Maximum Volume: 1100000
    Small Volume: 25000
  5 Sample:
    MUX Valve: 2
    Maximum Volume: 200000
    Small Volume: 10000
  Drain:
    MUX Valve: 7
    Maximum Volume: NaN
    Small Volume: 5000



