Bottle Volume: 1500
Container Volume: 25688.34
D Term: 0.05
Default Flow: 30000
I Term: 6
Operations:
- add
- remove
- fill
- empty
- automatic
P Term: 1.4
PVA Waiting Time: 50
Project Path: C:\Users\Operator\PelliKAn\2_TransferStage\2_Python_Scripts\GUI
Remaining Bottle Volume: 0.0
Selected Container: Drain
Selected Operation: add
