Container Volume: 0
Containers:
  1 Sample:
    MUX Valve: 1
    Maximum Volume: 180000
    Small Volume: 5000
  10 Sample:
    MUX Valve: 3
    Maximum Volume: 1100000
    Small Volume: 5000
  5 Sample:
    MUX Valve: 2
    Maximum Volume: 200000
    Small Volume: 5000
D Term: 0.05
Default Flow: 30000
I Term: 6
Operations:
- add
- remove
- fill
- empty
- automatic
P Term: 1.4
PVA Waiting Time: 1
Project Path: C:\Users\Operator\PelliKAn\2_TransferStage
Selected Container: 1 Sample
Selected Operation: add
